### ISSUE TITLE
No such file or directory: '/root/.ssh/config'

### ISSUE THREAD

**Issue by wtgg** [seamile/FastCopy#5]
No such file or directory: '/root/.ssh/config' 是什么情况？
手动touch /root/.ssh/config之后报错fcp: create channel failed due to ChannelException(2, 'Connect failed')

scp正常

**Comment by seamile** [comment]
> No such file or directory: '/root/.ssh/config' 是什么情况？
> 手动touch /root/.ssh/config之后报错fcp: create channel failed due to ChannelException(2, 'Connect failed')
> 
> scp正常

“.ssh/config 的未找到” 的问题确实是 Bug，新版本已经改过了，pip 更新一下 0.1.7 版就可以了 `pip install -U fastcopy`。

“Connect failed” 可能是因为你的服务端未安装，或者安装后未运行。可以在服务器执行：
```shell
pip install -U fastcopy
fcpd -d
```
